### ISSUE TITLE
Unknown/random crash when multiple aircraft are trying to land

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#439]
```
Exception of type `System.InvalidOperationException`: Cannot AddInfluence until previous influence is removed with RemoveInfluence
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(ValueTuple`2[] landingCells) in engine\OpenRA.Mods.Common\Traits\Air\Aircraft.cs:line 870
   at OpenRA.Mods.Common.Traits.Aircraft.AddInfluence(CPos landingCell) in engine\OpenRA.Mods.Common\Traits\Air\Aircraft.cs:line 880
   at OpenRA.Mods.Common.Activities.Land.Tick(Actor self) in engine\OpenRA.Mods.Common\Activities\Air\Land.cs:line 232
```

Reproduction steps:
- queue multiple move orders to move around in small area to a group of aircraft
- infantry (or other ground actors) on the ground might or might not be necessary

![Image](https://user-images.githubusercontent.com/119738087/263263673-c6e915e8-d2dc-4233-b7d0-d55b81816548.gif)

**Comment by michaeldgg2** [comment]
The bug was fixed in the engine with PR OpenRA/OpenRA#21346.
