### ISSUE TITLE
Crash in `CreateSmokeEffectWarhead`

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#456]
```
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (ucs_vehicles_spider_ii 302 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in OpenRA\OpenE2140\engine\OpenRA.Game\TraitDictionary.cs:line 84
   at OpenRA.Mods.OpenE2140.Warheads.CreateSmokeEffectWarhead.DoImpact(Target& target, WarheadArgs args) in OpenRA\OpenE2140\OpenRA.Mods.OpenE2140\Warheads\CreateSmokeEffectWarhead.cs:line 60
```

**Comment by GraionDilach** [comment]
I don't remember why now, but all my custom warheads include this block immediately after defining firedBy to prevent this crash.

```
			if (!target.IsValidFor(firedBy))
				return;
```
